import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const clashDisplay = localFont({
  src: [
    {
      path: "../../public/fonts/ClashDisplay-Variable.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/ClashDisplay-Variable.ttf",
      weight: "400",
    },
    {
      path: "../../public/fonts/ClashDisplay-Variable.ttf",
      weight: "500",
    },
  ],
  variable: "--font-clashdisplay",
});
export const metadata: Metadata = {
  title: "TonClaim",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable} font-clashDisplay text-white` }>
        {children}
      </body>
    </html>
  );
}
